/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pe.com.arland.cliente1.registro;

import org.junit.jupiter.api.Test;

import pe.com.arland.cliente1.registro.entity.VehiculoAutomovilBase;
import pe.com.arland.cliente1.registro.entity.factory.FabricaVehiculoElectricidad;
import pe.com.arland.cliente1.registro.entity.factory.IFabricaVehiculo;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
      App classUnderTest = new App();
      assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    
    
}
