/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pe.com.arland.cliente1.registro;

import java.util.Scanner;

import pe.com.arland.cliente1.registro.entity.VehiculoAutomovilBase;
import pe.com.arland.cliente1.registro.entity.VehiculoScooterBase;
import pe.com.arland.cliente1.registro.entity.factory.FabricaVehiculoElectricidad;
import pe.com.arland.cliente1.registro.entity.factory.FabricaVehiculoGasolina;
import pe.com.arland.cliente1.registro.entity.factory.IFabricaVehiculo;

public class App {
	
	 public static int nAutos = 3; 
	 public static int nScooters = 2; 
	  
    public String getGreeting() {
     	  
        Scanner reader = new Scanner(System.in); 
        IFabricaVehiculo fabrica; 
        VehiculoAutomovilBase[] autos = new VehiculoAutomovilBase[nAutos]; 
        VehiculoScooterBase[] scooters = new VehiculoScooterBase[nScooters]; 
        System.out.print("Desea utilizar " + 
          "vehiculos electricos (1) o a gasolina (2):"); 
        String eleccion = reader.next(); 
        if (eleccion.equals("1")) 
        { 
          fabrica = new FabricaVehiculoElectricidad(); 
        } 
        else 
        { 
          fabrica = new FabricaVehiculoGasolina(); 
        } 
        for (int index = 0; index < nAutos; index++) 
          autos[index] = fabrica.creaAutomovil("estandar",  
            "amarillo", 6+index, 3.2); 
        for (int index = 0; index < nScooters; index++) 
          scooters[index] = fabrica.creaScooter("clasico",  
            "rojo", 2+index); 
        for (VehiculoAutomovilBase auto: autos) 
          auto.mostrarCaracteristicas(); 
        for (VehiculoScooterBase scooter: scooters) 
          scooter.mostrarCaracteristicas(); 
    	
    	return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
